<?php
/**
 * Project: freelancercom-search
 *
 * @author Amado Martinez <amado@projectivemotion.com>
 */

return array (
    'scheme' => 'https',
    'host' => 'www.freelancer.com',
    'path' => '/ajax/table/project_contest_datatable.php',
    'query_arr' =>
        array (
            'sEcho' => '5',
            'iColumns' => '35',
            'sColumns' => '',
            'iDisplayStart' => '0',
            'iDisplayLength' => '10',
            'iSortingCols' => '1',
            'iSortCol_0' => '6',
            'sSortDir_0' => 'desc',
            'bSortable_0' => 'false',
            'bSortable_1' => 'false',
            'bSortable_2' => 'false',
            'bSortable_3' => 'true',
            'bSortable_4' => 'false',
            'bSortable_5' => 'false',
            'bSortable_6' => 'true',
            'bSortable_7' => 'false',
            'bSortable_8' => 'true',
            'bSortable_9' => 'true',
            'bSortable_10' => 'false',
            'bSortable_11' => 'false',
            'bSortable_12' => 'false',
            'bSortable_13' => 'false',
            'bSortable_14' => 'false',
            'bSortable_15' => 'false',
            'bSortable_16' => 'false',
            'bSortable_17' => 'false',
            'bSortable_18' => 'false',
            'bSortable_19' => 'false',
            'bSortable_20' => 'false',
            'bSortable_21' => 'false',
            'bSortable_22' => 'false',
            'bSortable_23' => 'false',
            'bSortable_24' => 'false',
            'bSortable_25' => 'false',
            'bSortable_26' => 'false',
            'bSortable_27' => 'false',
            'bSortable_28' => 'false',
            'bSortable_29' => 'false',
            'bSortable_30' => 'false',
            'bSortable_31' => 'false',
            'bSortable_32' => 'false',
            'bSortable_33' => 'false',
            'bSortable_34' => 'false',
            'keyword' => '',
            'featured' => 'false',
            'fulltime' => 'false',
            'nda' => 'false',
            'qualified' => 'false',
            'sealed' => 'false',
            'urgent' => 'false',
            'guaranteed' => 'false',
            'highlight' => 'false',
            'private' => 'false',
            'top' => 'false',
            'type' => 'f',
            'budget_min' => '160',
            'budget_max' => '350',
            'contest_budget_min' => 'false',
            'contest_budget_max' => 'false',
            'hourlyrate_min' => 'false',
            'hourlyrate_max' => 'false',
                /** @see li-skills.html **/
            'skills_chosen' => '3,31',
            'verified_employer' => 'false',
            'bidding_ends' => 'N/A',
            'bookmarked' => 'false',
            'countries' => 'false',
            'languages' => 'en',
            'hourlyProjectDuration' => 'false',
            'advancedFilterPanelView' => '',
            'disablePushState' => 'false',
            'pushStateRoot' => '/jobs',
            'lat' => 'false',
            'lon' => 'false',
            'local' => 'false',
            'location' => '[object Object]',
            'ul' => 'en',
            'uc' => '1',
        /** @see li-skills.html **/
            'xpbonus_catIds' => '15',
            'jobIdEnable' => 'on',
            'status' => 'open',
            '_' => time(),
        ),
);